// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1I3-PJUx8v-nqnc3vM1-0PkE4vxcbSPk',
    appId: '1:936293592550:web:b0e088fea33a36a20dfa27',
    messagingSenderId: '936293592550',
    projectId: 'mywalletapp-65c15',
    authDomain: 'mywalletapp-65c15.firebaseapp.com',
    storageBucket: 'mywalletapp-65c15.firebasestorage.app',
    measurementId: 'G-C73BXP6SSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Nh4gJr2Mywy3A32Q_OPU4ENc0lAa6Y0',
    appId: '1:936293592550:android:f31b860d70158f1e0dfa27',
    messagingSenderId: '936293592550',
    projectId: 'mywalletapp-65c15',
    storageBucket: 'mywalletapp-65c15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6k-u4kHQW40XkLxMt_vwd7iebjkaepXM',
    appId: '1:936293592550:ios:35c9d379ce85a3130dfa27',
    messagingSenderId: '936293592550',
    projectId: 'mywalletapp-65c15',
    storageBucket: 'mywalletapp-65c15.firebasestorage.app',
    iosBundleId: 'com.newagedavid.myWalletApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6k-u4kHQW40XkLxMt_vwd7iebjkaepXM',
    appId: '1:936293592550:ios:35c9d379ce85a3130dfa27',
    messagingSenderId: '936293592550',
    projectId: 'mywalletapp-65c15',
    storageBucket: 'mywalletapp-65c15.firebasestorage.app',
    iosBundleId: 'com.newagedavid.myWalletApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1I3-PJUx8v-nqnc3vM1-0PkE4vxcbSPk',
    appId: '1:936293592550:web:7040a28832ee11c50dfa27',
    messagingSenderId: '936293592550',
    projectId: 'mywalletapp-65c15',
    authDomain: 'mywalletapp-65c15.firebaseapp.com',
    storageBucket: 'mywalletapp-65c15.firebasestorage.app',
    measurementId: 'G-F5GH80MW4G',
  );

}